name: super_enum
description: Create super-powered enums similar to sealed classes in Kotlin.
version: 0.7.0
homepage: https://github.com/ride4sun/super_enum

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.7.0
  equatable: ^2.0.3

# Adding dev dependencies
# just for showcasing an example
dev_dependencies:
  http: ^0.13.4
  build_runner: ^2.1.4

